### ISSUE TITLE
Gloomrot Update

### ISSUE THREAD

**Issue by decaprime** [decaprime/LeadAHorseToWater#16]
- [x] Mostly needs extensions for avoiding AOT
- [x] updated team checker
- [x] Update package versions
- [ ] Remove extraneous logging outside of debug channel, tone down debug

**Comment by skythebro** [comment]
Hey, I'm not sure if you already found a replacement for the Teamchecker but I decided to try out modding (only did a small mod for SoTF before) and I think I figured out a way to check if a horse is a unit and therefore a wild horse. 

I don't know if this is the correct way to do it but I've tested the mod by running it on my own private server (for me and my gf) and the tamed horses drink water while near a well and the untamed ones don't.

Here's the updated method:
```
private static bool IsHorseWeFeed(Entity horse, ComponentSystemBase instance)
        {
            EntityManager em = instance.World.EntityManager;
            ComponentDataFromEntity<Team> getTeam = instance.GetComponentDataFromEntity<Team>();

            if (em.HasComponent<Team>(horse))
            {
                var teamhorse = getTeam[horse];
                var isUnit = Team.IsInUnitTeam(teamhorse);

                _log?.LogDebug(isUnit
                    ? (BepInExInfoLogInterpolatedStringHandler)
                    $"Horse <{horse.Index}> IsUnit={false} this horse is a tamed horse"
                    : $"Horse <{horse.Index}> IsUnit={true} this horse is an untamed horse");
                // Wild horses are Units, appear to no longer be units after you ride them.
                return !isUnit;
            }

            // Handle the case when the horse entity does not have the Team component.
            _log?.LogDebug($"Horse <{horse.Index}> does not have Team component. {horse}");
            return false;
        }
```
The logging doesn't really need to be there but it was there to make sure it was working at first.
I hope this is of some use to you.
